version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask_backend
    expose:
      - "5000"

  nginx:
    build: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
